
name: Go

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.3

    - name: Go version
      run: go version

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...
      env:
        OPENAI_TOKEN: '${{ secrets.OPENAI_TOKEN }}'

    - name: Notify reviewer if tests pass